### ISSUE TITLE
Example or documentation for embedded_schema

### ISSUE THREAD

**Issue by rrevanth** [jakub-zawislak/formex#1]
This is just a question rather than issue.

Is there any documentation where I can find how to use embedded_many or embedded_one with formex.

Thank you for this module! It's awesome! :D

**Comment by rrevanth** [comment]
I am getting this error when using it with embeds_many 


`Server: localhost:4000 (http)
Request: GET /organizations/new
** (exit) an exception was raised:
    ** (RuntimeError) casting embeds with cast/3 is not supported, use cast_embed/3 instead
        (ecto) lib/ecto/changeset.ex:499: Ecto.Changeset.type!/2
        (ecto) lib/ecto/changeset.ex:474: Ecto.Changeset.process_param/8
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:450: Ecto.Changeset.do_cast/7
        (formex) lib/formex/builder.ex:63: Formex.Builder.create_changeset/2
        (scheduld) web/controllers/organization_controller.ex:12: Scheduld.OrganizationController.new/2
        (scheduld) web/controllers/organization_controller.ex:1: Scheduld.OrganizationController.action/2
        (scheduld) web/controllers/organization_controller.ex:1: Scheduld.OrganizationController.phoenix_controller_pipeline/2
        (scheduld) lib/scheduld/endpoint.ex:1: Scheduld.Endpoint.instrument/4
        (scheduld) lib/phoenix/router.ex:261: Scheduld.Router.dispatch/2
        (scheduld) web/router.ex:1: Scheduld.Router.do_call/2
        (scheduld) lib/scheduld/endpoint.ex:1: Scheduld.Endpoint.phoenix_pipeline/1
        (scheduld) lib/plug/debugger.ex:123: Scheduld.Endpoint."call (overridable 3)"/2
        (scheduld) lib/scheduld/endpoint.ex:1: Scheduld.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/jinx/Workspace/private/Phoenix/phx-1.2/scheduld-sentinel/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
`

I have organization table with embeds_many of address.

**Comment by rrevanth** [comment]
`Request: GET /organizations
** (exit) an exception was raised:
    ** (ArgumentError) unknown field `formex_delete`. Only fields, embeds and associations (except :through ones) are supported in changesets
        (ecto) lib/ecto/changeset.ex:503: Ecto.Changeset.type!/2
        (ecto) lib/ecto/changeset.ex:474: Ecto.Changeset.process_param/8
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:450: Ecto.Changeset.do_cast/7
        (ecto) lib/ecto/changeset.ex:417: Ecto.Changeset.do_cast/4
        (formex) lib/formex/builder.ex:119: anonymous fn/4 in Formex.Builder.cast_embedded_forms/2
        (phoenix_ecto) lib/phoenix_ecto/html.ex:227: Phoenix.HTML.FormData.Ecto.Changeset.to_changeset/4
        (phoenix_ecto) lib/phoenix_ecto/html.ex:78: anonymous fn/8 in Phoenix.HTML.FormData.Ecto.Changeset.to_form/4
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_ecto) lib/phoenix_ecto/html.ex:76: Phoenix.HTML.FormData.Ecto.Changeset.to_form/4
        (phoenix_html) lib/phoenix_html/form.ex:273: Phoenix.HTML.Form.inputs_for/4
        (formex) lib/formex/view_collection.ex:195: Formex.View.Collection.formex_collection_items/1
        (formex) lib/formex/view_collection.ex:155: Formex.View.Collection.formex_collection/5
        (phoenix_html) lib/phoenix_html/form.ex:239: Phoenix.HTML.Form.form_for/4
        (formex) lib/formex/view_collection.ex:252: Formex.View.Collection.generate_collection_prototype/5
        (formex) lib/formex/view_collection.ex:152: Formex.View.Collection.formex_collection/5
        (scheduld) web/templates/organization/form.html.eex:17: anonymous fn/2 in Scheduld.OrganizationView.form.html/1
        (phoenix_html) lib/phoenix_html/form.ex:239: Phoenix.HTML.Form.form_for/4
        (scheduld) web/templates/organization/form.html.eex:1: Scheduld.OrganizationView."form.html"/1
        (scheduld) web/templates/organization/index.html.eex:34: Scheduld.OrganizationView."index.html"/1
`

I think i am getting somewhere but I am stuck at this error. the formex changeset builder is considering formex_delete as a field in embed_schema.

Am I doing something wrong here?

**Comment by jakub-zawislak** [comment]
Hey. `embedded_many` and `_one` should just work. But I have to admit that I tested only the case when we have `embedded_schema` + `embedded`, not `schema` + `embedded`. You just want to use the second case, aren't you? So I have to check it

**Comment by rrevanth** [comment]
Hey,

yeah. this is the schema i am trying.

```
  schema "organizations" do
    field :name, :string
    
    embeds_many :addresses, Address do
      field :first_name, :string
      field :last_name, :string
      field :email, :string
      field :addr_1, :string
      field :addr_2, :string
      field :phone, :string
      field :state, :string
      field :country, :string
      field :zip, :string
      formex_collection_child()
    end
```

Can you put up some steps on how to do it. I am trying but it feels like i'm not doing the right way!


These are the steps I followed.

Created the above schema.

Created two formex_forms
- One for organization
```
  def build_form(form) do
    form
      |> add(:name, :text_input, label: "Name")
      |> add(:addresses, AddressType)
```
- One for addresses
```
  def build_form(form) do
    form
    |> add(:first_name, :text_input)
    |> add(:last_name, :text_input)
    |> add(:email, :text_input)
    |> add(:addr_1, :text_input)
    |> add(:addr_2, :text_input)
    |> add(:state, :text_input)
    |> add(:country, :text_input)
    |> add(:zip, :text_input)
    |> add(:phone, :text_input)
  end
```
and then made changes in controller,new form and my form.html.eex looks like this :

`
          <%= formex_row f, :name %>
          <%= formex_collection f, :addresses %>
`

But the address fields are not showing up. :(

**Comment by jakub-zawislak** [comment]
Hey,

I just tested:

```elixir
  schema "users" do
    field :first_name, :string
    field :last_name, :string

    embeds_many :schools, School do
      field :name, :string
      formex_collection_child()
    end
  end
```

It works. At first I forgot about `formex_collection_child()` and got the same error 😄  

The `formex_delete` field should be created by `formex_collection_child()`. When I write `IO.inspect %User.Address{}` I can see it. Could you run `IO.inspect %Organization.Address{}` and tell if that field exists?

**Comment by jakub-zawislak** [comment]
I didn't refresh this page so I didn't see that you edited comment 8 hours ago. So I'm going to write a new comment instead of edit 😄 

> But the address fields are not showing up. :(

What do you mean? If you don't have any addresses in database, you should just see `Add` button. In my User - Schools form the `<%= formex_collection ... %>` produces:

```html
<div class="formex-collection" data-prototype="&lt;div class=&quot;formex-collection-items&quot;&gt;&lt;div class=&quot;formex-collection-item formex-collection-item-new&quot;&gt;&lt;a class=&quot;formex-collection-item-remove&quot; data-confirm=&quot;Are you sure?&quot; href=&quot;#&quot;&gt;&amp;times;&lt;/a&gt;&lt;div class=&quot;form-group required&quot;&gt;&lt;label class=&quot;control-label &quot; for=&quot;user_schools_0_name&quot;&gt;Nazwa&lt;/label&gt;&lt;input class=&quot;form-control &quot; id=&quot;user_schools_0_name&quot; name=&quot;user[schools][0][name]&quot; type=&quot;text&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;">
  <div class="formex-collection-items"></div>
  <button class="btn btn-default formex-collection-add " type="button">Add</button>
</div>
```

You have to create a JS file which will import `formex` JS library. It's described here: https://hexdocs.pm/formex/Formex.Type.html#module-collections-of-forms
When you do it, the `Add` button should work.

By the way, I see now that deletion of items from `embeds_many` doesn't work, I need to better test that `embedded` stuff.

**Comment by rrevanth** [comment]
@jakub-zawislak yeah, the add button is showing up for me as well

this is the html that it generates : 

```html
<div class="formex-collection" data-prototype="<div class=&quot;formex-collection-items&quot;><div class=&quot;formex-collection-item formex-collection-item-new&quot;><a class=&quot;formex-collection-item-remove&quot; data-confirm=&quot;Are you sure?&quot; href=&quot;#&quot;>&amp;times;</a><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_first_name&quot;>First Name</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_first_name&quot; name=&quot;organization[addresses][0][first_name]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_last_name&quot;>Last Name</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_last_name&quot; name=&quot;organization[addresses][0][last_name]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_email&quot;>Email</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_email&quot; name=&quot;organization[addresses][0][email]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_addr_1&quot;>Address Line 1</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_addr_1&quot; name=&quot;organization[addresses][0][addr_1]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_addr_2&quot;>Address Line 2</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_addr_2&quot; name=&quot;organization[addresses][0][addr_2]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_city&quot;>City</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_city&quot; name=&quot;organization[addresses][0][city]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_state&quot;>State</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_state&quot; name=&quot;organization[addresses][0][state]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_country&quot;>Country</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_country&quot; name=&quot;organization[addresses][0][country]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_zip&quot;>Zip</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_zip&quot; name=&quot;organization[addresses][0][zip]&quot; type=&quot;text&quot;></div></div><div class=&quot;form-group required&quot;><label class=&quot;control-label &quot; for=&quot;organization_addresses_0_phone&quot;>Phone</label><div class=&quot;&quot;><input class=&quot;form-control &quot; id=&quot;organization_addresses_0_phone&quot; name=&quot;organization[addresses][0][phone]&quot; type=&quot;text&quot;></div></div></div></div>">
  <div class="formex-collection-items"></div>
  <div class="form-group">
    <div class=" ">
      <button class="btn btn-default formex-collection-add "  type="button">Add</button>
    </div>
  </div>
</div>
```


I also have the js file but the add button not adding new subform! anywhere else that I might have done something!

**Comment by jakub-zawislak** [comment]
Have you checked browser console? Any errors in console when you click the button?

**Comment by rrevanth** [comment]
I checked that. I see no errors there as well.

**Comment by jakub-zawislak** [comment]
Are you sure that this JS is loaded? Print some `console.log()`?

**Comment by rrevanth** [comment]
Yep, it's printing the log in console.

[imgur link](http://imgur.com/a/7OUpa)

**Comment by jakub-zawislak** [comment]
Oops, I forgot to compile that JS library. I just published 0.4.5 version of formex, so update and try again.

**Comment by rrevanth** [comment]
I put the mix dependency as master rather than from hex.

I also tried with 0.4.5 just now. Didn't have luck with that either.

Is it possible for you to upload the demo you created to github so that I will check that with mine for errors.

I might have done some really dumb thing and can't seem to figure it out . 😥

**Comment by jakub-zawislak** [comment]
Just published a new update (still 0.4.5). After download run `npm update formex`

**Comment by rrevanth** [comment]
Awesome. That solved the display issues! 

But now there seems to be some template issues ...

This is the error that is showing up : 

`
lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %App.Embeds.Address{addr_1: "l", addr_2: "l", city: "l", country: "l", email: "l", first_name: "l", formex_delete: nil, id: "ec57a251-13b7-483b-b850-6136bde1f1de", last_name: "l", phone: "l", state: "l", zip: "l"}
`
The data is added to the database as well seems like the Phoenix.HTML.Safe error.

**Comment by jakub-zawislak** [comment]
Can you show me your eex template?

**Comment by rrevanth** [comment]
Sure.

```html
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
        <h3 class="box-title">Listing organizations</h3>
        <div class="scrollable">
            <div class="table-responsive">
                <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                    <thead>
                        <tr>
                              
                          <th>Name</th>
                              
                          <th>Addresses</th>
                        
                        </tr>
                    </thead>
                    <tbody>
                    <%= for organization <- @organizations do %>
                        <tr>
                        
                            <td><%= organization.name %></td>
                        
                            <td><%= organization.addresses %></td>
                        
                        </tr>
                    <% end %>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2">
                                <button type="button" class="btn btn-info btn-rounded" data-toggle="modal" data-target="#add-organization">Add New organization</button>
                            </td>
                            <div id="add-organization" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="organizationLabel" aria-hidden="true">
                                <%= render "form.html", form: @form, action: organization_path(@conn, :create) %>
                            </div>
                            <td colspan="7">
                                <div class="text-right">
                                    <ul class="pagination"> </ul>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
  </div>
</div>
```

**Comment by rrevanth** [comment]
@jakub-zawislak I found it. seems like we cant display the list directly.

I converted it by Poison.encode and it displayed it although like a json value.

Thank you for immediate responses for my questions! 😄

**Comment by jakub-zawislak** [comment]
Awesome! But as I found out today, edition and deletion of that embedded schema doesn't work properly. I will fix it soon

**Comment by rrevanth** [comment]
cool!

**Comment by rrevanth** [comment]
Hey, one more question , I have a user_id that my organization belongs to that I will fetch from my conn and add it to changeset. 

Since there is no changeset in the controller. How should I go add it without creating the field in type and form.

**Comment by jakub-zawislak** [comment]
There is one callback
https://hexdocs.pm/formex/Formex.Type.html#c:changeset_after_create_callback/1
Maybe it will help?

```elixir
defmodule App.OrganizationType do
  use Formex.Type

  def build_form(form) do
    form
    |> add(:name, :text_input)
    ...
  end

  def changeset_after_create_callback(changeset) do
    put_change(changeset, :user_id, ...) # but... how you can pass here something? :D
  end
end
```

I think I should create another callback that would be an anonymous function in controller. It would help?

Edit:

For now you can change
```elixir
App.OrganizationType
|> create_form(organization, organization_params)
|> update_form_data
```
to
```elixir
form = App.OrganizationType
|> create_form(organization, organization_params)

# do here what you want with `form.changeset`

update_form_data(form)
```

**Comment by rrevanth** [comment]
I guess, i tried putting the change set and trying to pass it to create_form and before insert form.. 
May be doing something elixir way to access change set in-between so we can make our modifications since it is a frequent need i guess. ☺

**Comment by jakub-zawislak** [comment]
For now you can change
```elixir
App.OrganizationType
|> create_form(organization, organization_params)
|> update_form_data
```
to
```elixir
form = App.OrganizationType
|> create_form(organization, organization_params)

# do here what you want with `form.changeset`

update_form_data(form)
```

**Comment by rrevanth** [comment]
Can you give an example of put_changeset in between.

I am trying this :

form.changeset = Ecto.Changeset.put_change(form.changeset, "user",
conn.current_user)

but it's giving error :

** (CompileError) web/controllers/organization_controller.ex:20:
cannot invoke remote function form.changeset/0 inside match
    web/controllers/organization_controller.ex:17: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

**Comment by jakub-zawislak** [comment]
In Elixir you cannot write `map.key = something`. You can, for example:
```elixir
changeset = form.changeset
changeset = Ecto.Changeset.put_change(changeset, "user", conn.current_user)
form = Map.put(form, :changeset, changeset)
```
You can also try
https://hexdocs.pm/elixir/Kernel.html#put_in/3

**Comment by rrevanth** [comment]
@jakub-zawislak wow.. I found a strange thing here. I already tried the above code while trying different variations and the changeset still hasn't changed but for debug purposes I kept a IO.inspect before and after put_changeset .

Today I tried the code without the IO.inspect before the changeset and it worked like a charm, dunno how though! :|


I found one more issue (sorry I keep throwing a lot of issues 😥 ) : 

- I added a modal form from index page where I can add the values and collection directly from index. Strangely, the address params are not added in the organization_params whereas they are properly added when I add them from organizations/new url.

Any idea where I  might have gone wrong. I changed the index of the controller to this : 


``` html
    organizations = Repo.all(Organization)
    form = create_form(Scheduld.OrganizationType, %Organization{})
    render(conn, "index.html", organizations: organizations, form: form)

```

**Comment by jakub-zawislak** [comment]
Your controller code looks ok, and I think it should work. Could you compare params that comes to controller in that two cases? I mean the modal and the `organizations/new` page.

**Comment by rrevanth** [comment]
The address is not being passed in params when added from organizations/index whereas is sent from organizations/new. I hope this is what you are asking.

**Comment by rrevanth** [comment]
@jakub-zawislak  I see we can add opts in create_form . Will the opts be passed to changeset as well?

**Comment by jakub-zawislak** [comment]
I didn't write any documentation about it yet 😄 . You can, for example, pass there current logged user. Then access it inside a `build_form` callback by `form.opts[:user]`.

I used this to get options in select that belongs to user:

```elixir
form = create_form(TransferType, %Transfer{}, %{}, user: user)
```

```elixir
  def build_form(form) do
    form
    |> add(:user_account_id, SelectAssoc,
      query: fn query ->
        query
        |> Account.by_user(form.opts[:user])
      end
  end
```

BTW. Do you still have problem with form inside modal? Could you put example of code online?

**Comment by rrevanth** [comment]
@jakub-zawislak Wow, I was just about to mention that problem and you have already solved it 👍  

I solved the problem with modal, it seems to be related to some template errors in my form.html.eex 🤕 

One other problem i am facing is not finding array field to the form. Is there any input field for array in formex?

my schema has this

:option_values, {:array, :string}

I suppose CustomField behaviour is way to accomplish this!?

Also, it doesn't respect the changeset validations in my model. Is it expected?

**Comment by jakub-zawislak** [comment]
Oh, I have not heard of arrays in ecto before. First time I used Postgres was when you created that issue 😄  I have to read about this. And no, I think that CustomField will not help.

**Comment by rrevanth** [comment]
Oh .. 

With Phoeinx Form, we can create one as follows : 

http://stackoverflow.com/questions/41404526/phoenix-form-field-for-array-model-data-type

or 

https://medium.com/@chipdean/phoenix-array-input-field-implementation-7ec0fe0949d

Jose wrote a post on dynamic forms with phoenix : 

http://blog.plataformatec.com.br/2016/09/dynamic-forms-with-phoenix/

It would be helpful to have input_helpers to define custom fields that will be used with formex.

I am trying to integrate them on my end but it's kinda difficult considering my knowledge in elixir as well as the module. 😄

**Comment by rrevanth** [comment]
@jakub-zawislak Hey, sorry to bug you again : 

I have the following schemas : 

Product : 
`
    create table(:products) do
      add :name, :string
      add :description, :string

`

Options : 

`
   create table(:options) do
      add :description, :string [eg : size,weight,color etc.,]
`

Product_options : 

`
    create table(:product_options) do
      add :values, {:array, :string}, default: [] ( contains all possible values for one product and option)
      add :product_id, references(:products, on_delete: :nothing)
      add :option_id, references(:options, on_delete: :nothing)
`

I want to create a inventory where options is a map of values for each option that the product has through product_options.

The schema looks like this : 

`
    create table(:product_inventory) do
      add :options, :map
      add :product_id, references(:products, on_delete: :nothing)
`

I am trying to create a form where the user once selects a product_id from select, he will be displayed all the options and their values from product_options.

Is there a way to do that via Formex? I am unable to figure out how to make the form display dynamically based on selecting product_id which is in the form itself.

**Comment by rrevanth** [comment]
@jakub-zawislak Hey, I want to make a custom input for map variable that I am creating.

I want to have a select option rather than formex_row in my template's formex_for loop.

How can I do it!

**Comment by jakub-zawislak** [comment]
Could you next time create a new issue? There is multiple offtopics now 😄 

> I want to have a select option rather than formex_row

You want to display just an input instead of whole row? You are right, I have to do it. In Symfony there is the `form_widget` that generates simple "widget" (input) without label etc. 

Maybe you ask about your pull request, I didn't reviewed it yet.

**Comment by rrevanth** [comment]
Sorry, it's just that they are more of an off topic questions and i'm not sure whether they are already implemented in formex.

Regarding the pull request, I am able to integrate the array input for my project and it has several hard coded stuff. I just created the request to offload some effort you need to put from scratch
