### ISSUE TITLE
JS lib, collections, handling multi-level collections

### ISSUE THREAD

**Issue by tmbb** [jakub-zawislak/formex#10]
https://github.com/jakub-zawislak/formex/blob/0d47947d860b59e378cfc9f4d9ae395523bff2d4/web/static/js/formex.js#L38

**Comment by jakub-zawislak** [comment]
😄 
This file was originally copied from another project and I didn't finish it yet. It's all about working with collections in collections in collections... It should be the only file with polish comments. I will change this issue name to that collections problem.
