### ISSUE TITLE
Cannot use distillery for release due to function capture

### ISSUE THREAD

**Issue by realprabs** [jakub-zawislak/formex#12]
My config looks like this:
```
config :formex,
  repo: App.Repo,
  validator: Formex.Ecto.ChangesetValidator,
  translate_error: &AppWeb.ErrorHelpers.translate_error/1
```
The translate error function capture is not compatible with distillery, so I can't build a release. https://github.com/bitwalker/distillery/issues/185

If I don't use translate_error config option, I get `BadFunctionError: expected a function, got: nil
` in `lib/formex/validator.ex:96`

Any possible solution?

**Comment by jakub-zawislak** [comment]
Fixed in 0.6.2. Now the `translate_error` option is really optional. If you don't need to translate errors, then you can omit this setting. 

Anyway, if you need to translate errors while using distillery, you can now set this option in every type file in this way:

  ```elixir
  def build_form(form) do
    form
    |> add(:name, :text_input)
    # ...
  end

  def translate_error, do: &AppWeb.ErrorHelpers.translate_error/1
  ```
