### ISSUE TITLE
Is there a way to do an array with checkboxes?

### ISSUE THREAD

**Issue by coderberry** [jakub-zawislak/formex#14]
I have an array column with roles `{:array, :string} => ["admin", "developer", "sponsor"]`

I would like to have a checkbox for each one and if checked, they update the array with the content. Is that possible with Formex?

**Comment by jakub-zawislak** [comment]
Fixed in formex_ecto `0.1.9` and formex `0.6.5`
jakub-zawislak/formex_ecto#5
