### ISSUE TITLE
Hidden Input

### ISSUE THREAD

**Issue by JohnKacz** [jakub-zawislak/formex#19]
Is there a way to make an input hidden? 

I'm looking to set a boolean in a nested form. I'm using `custom_value` to conditionally set it, but I'd like it hidden as well. I can do it with CSS but I thought there should be some better way.

**Comment by jakub-zawislak** [comment]
```elixir
form
|> add(:name, :hidden_input, ...)
```
This `:hidden_input` argument is just a function name from [Phoenix.HTML.Form](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html)

**Comment by JohnKacz** [comment]
Ah yes, of course. Thanks!

**Comment by JohnKacz** [comment]
Hmm, now I'm struggling to figure out how to hide the label?

**Comment by jakub-zawislak** [comment]
[Formex.View docs](https://hexdocs.pm/formex/Formex.View.html#formex_input/3)
You have functions - `formex_input` which renders input, `formex_label` which renders label and `formex_row` which renders both of them. So you have to use just `formex_input` to render that hidden input. 

If you are using `formex_rows` to generate all rows at once, then you have to convert it to multiple `formex_row` and one `formex_input`.

**Comment by JohnKacz** [comment]
Thanks so much @jakub-zawislak
