### ISSUE TITLE
Are there date, time, datetime form elements in formex

### ISSUE THREAD

**Issue by igormisha** [jakub-zawislak/formex#21]
I want to add fields like date_select, time_select, datetime_select in formex? And where can I find all available for formex input types in the documentation?

**Comment by jakub-zawislak** [comment]
You can use any function from [Phoenix.HTML.Form](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html) that renders input. 

For example:
```elixir
form
|> add(:title, :text_input)
```
the `:text_input` argument is the name of function from `Phoenix.HTML.Form`

**Comment by igormisha** [comment]
Thanks, it's not explicitely mentioned in the documentation, so I asked.
