### ISSUE TITLE
Module not found: Error: Can't resolve 'formex'

### ISSUE THREAD

**Issue by igormisha** [jakub-zawislak/formex#22]
My installation is fresh new Phoenix 1.4, so there is a webpack.js project builder.

I added a dependency to the /assets/package.json file and it looks like this:
```
  "dependencies": {
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "formex": "file:../deps/formex"
  }

```
And added a line into /assets/js/app.js according to the documentation:

`import {Collection} from 'formex'`

But got the error:
```
ERROR in ./js/app.js
Module not found: Error: Can't resolve 'formex' in 'd:\test\hello\assets\js'
```

**Comment by igormisha** [comment]
I changed the line:
`import {Collection} from 'formex'`
to
`import {Collection} from '../../deps/formex'`
in the assets/js/app.js file
And error is gone but the Add button doesn't work, there are no errors in the browser console.

**Comment by jakub-zawislak** [comment]
Did you run `npm install` after including formex in package.json?

**Comment by igormisha** [comment]
No, I didn't.
Now I ran it and changed back the line in app.js to 
import {Collection} from 'formex'
And everything works, thanks!
