### ISSUE TITLE
SelectAssoc not working for many_to_many

### ISSUE THREAD

**Issue by rrevanth** [jakub-zawislak/formex#5]
I am testing the many_to_many SelectAssoc for product to options many to many schema.

It is showing this error : 

key :name not found in: %App.Option{__meta__: #Ecto.Schema.Metadata<:loaded, "options">, description: "opt1", factory: #Ecto.Association.NotLoaded<association :factory is not loaded>, factory_id: 1, id: 6, inserted_at: #<DateTime(2017-04-18T02:00:39Z Etc/UTC)>, products: #Ecto.Association.NotLoaded<association :products is not loaded>, updated_at: #<DateTime(2017-04-18T02:00:39Z Etc/UTC)>}

It boils down to select_assoc.ex line 208 where row.name cannot be fetched from assoc.

**Comment by rrevanth** [comment]
It can be added from options form but not products form.

**Comment by jakub-zawislak** [comment]
https://hexdocs.pm/formex/Formex.CustomField.SelectAssoc.html#module-options

Use the `:choice_label` option. In your case it should be `choice_label: :description`
