### ISSUE TITLE
SelectAssoc inside embeds

### ISSUE THREAD

**Issue by rrevanth** [jakub-zawislak/formex#6]
Is there any way we can use selectassoc field type inside embeds

Like select element for posts inside embeds?

**Comment by jakub-zawislak** [comment]
Hey, I have tested the SelectAssoc inside `embeds_many` and it just works. What is your problem?

**Comment by rrevanth** [comment]
Oh.. It didn't work for me when I tried.

I worked around selectassoc with another logic. I will try it again and update my status.

**Comment by jakub-zawislak** [comment]
My code:

```elixir
embeds_many :schools, School do
  field :name, :string
  belongs_to :city, App.City
  formex_collection_child()
end
```

```elixir
def build_form(form) do
  form
  |> add(:name, :text_input)
  |> add(:city_id, SelectAssoc)
end
```

**Comment by rrevanth** [comment]
Sorry, my bad : 

I am looking for different thing :  It seems the model im embedding is many_to_many

Here are my schemas : 

```
  schema "products" do
    field :name, :string
    field :description, :string

    many_to_many :options, Option, join_through: ProductOption, on_replace: 
```

```
  schema "product_options" do
    field :value, :string

    belongs_to :product, Product
    belongs_to :option, Option

```


```
  schema "options" do
    field :description, :string

    many_to_many :products, Product, join_through: ProductOption, on_replace: :delete
  end

```

```
  embedded_schema do
    belongs_to :options, Scheduld.Option
    field :value, :string
    formex_collection_child()
  end
```

```
  def build_form(form) do
    form
      |> add(:name, :text_input, label: "Name")
      |> add(:description, :text_input, label: "Description")
      |> add(:sku, :text_input, label: "Sku")
      |> add(:options, OptionsType, required: false)
  end
```

And with this it's giving error saying : 

function nil.related/0 is undefined or private for option_id

**Comment by jakub-zawislak** [comment]
I don't see any select in this code

An error `function nil.related/0 is undefined` is related with form collections. In which file and line that error occurs?

**Comment by rrevanth** [comment]
It's in options_type.ex

```
  def build_form(form) do
    form
      |> add(:option_id, SelectAssoc, label: "Option",choice_label: :description, phoenix_opts: [prompt: "Choose Option"])
      |> add(:value, :text_input, label: "Value")
  end
```

In the above file, the option_id line.

**Comment by jakub-zawislak** [comment]
When you access key `:options` from module `Product`, you get `Option` module, not `ProductOption` join. So in `OptionType` you are trying to get `option_id` which didn't exists in `Option` 😄 

It could work if it would be `has_many` instead of `many_to_many`. Unfortunately then you will lost `many_to_many` features 😞  But you can try to use `has_many` and `many_to_many` simultaneously, maybe it will not break anything

**Comment by rrevanth** [comment]
Oh, Is there anything I can try from my end using formex?

I don't understand the part of using has_many and many_to_many simultaneously..

Do you mean using like this : 
```
has_many :options, Option, join_through: ProductOption
many_to_many :options, Option, join_through: ProductOption
```

**Comment by jakub-zawislak** [comment]
Like this. I didn't tested it, but maybe it will work 😄 

```elixir
has_many :options_only_for_formex, ProductOption
many_to_many :options, Option, join_through: ProductOption
```

```elixir
  def build_form(form) do
    form
      |> add(:name, :text_input, label: "Name")
      |> add(:description, :text_input, label: "Description")
      |> add(:sku, :text_input, label: "Sku")
      # also renamed OptionsType to ProductOptionType
      |> add(:options_only_for_formex, ProductOptionType, required: false)
  end
```

**Comment by rrevanth** [comment]
Ok, I will try this and check if everything is working fine 😄
