### ISSUE TITLE
Module attribute for @repo evaluates to nil

### ISSUE THREAD

**Issue by seanwash** [jakub-zawislak/formex#7]
Hey there!

I've run into this issue a couple times now, where `@repo Application.get_env(:formex, :repo)` evaluates to `nil`, which causes issues like `** (UndefinedFunctionError) function nil.preload/2 is undefined or private`. So far I've been able to get things back on track by running `mix deps.compile --force`, but it doesn't seem like that's something that should have to be done occasionally.

I'll keep my eyes open to see if I can't find out how I'm causing this to happen.

**Comment by jakub-zawislak** [comment]
I think that you didn't config formex properly.

https://github.com/jakub-zawislak/formex#installation

config/config.exs (from your Phoenix app)

```elixir
config :formex,
  repo: App.Repo
```

**Comment by seanwash** [comment]
I triple checked the config when I first encountered the issue.

My config is as follows:

```
config :formex,
  repo: MyApp.Repo,
  translate_error: &MyApp.ErrorHelpers.translate_error/1,
  template: Formex.Template.BootstrapVertical
```

**Comment by jakub-zawislak** [comment]
So it should work 😄  could you give me full error log?

**Comment by seanwash** [comment]
If it happens again I can do that! The trace is already too far back in the history to be able to get at it.

Ps, thanks for building Formex!

**Comment by jakub-zawislak** [comment]
Compilation of formex should be done after config you app. So if you did it in the wrong order, recompilation is needed
