### ISSUE TITLE
Ability to get options for select via ajax

### ISSUE THREAD

**Issue by jakub-zawislak** [jakub-zawislak/formex#9]
@tmbb

**Comment by tmbb** [comment]
### Frontend

Some questions:

* What level of browser support do we want?
* Do we want to ditch JQuery? Doing so will probably limit our options in terms of browser support (but I don't know much about the details of frontend programming)

[This library](https://github.com/jshjohnson/Choices) seems cool, but it's IE11+. 
If we're willing to have JQuery we can have Select2, of course, or any of the jquery-dependent options.

### Backend

What are you planning for the backend part? The obvious solution would be having a centralized FormexController (really just a normal controller) that the user would add to the routes. I can think of more "magical" solutions, but they don't seem to save any typing unless you want to work on the (very) deep end of the meta-programming tool. And in any case they would mess with the ability to have filters or proper authorization.

So my vote is just having a normal phoenix controller that receives and emits JSON.

**Comment by tmbb** [comment]
To add to the above: I don't think that there should be only a single controller, of course. You'll want to have at least one controller per permission level (admin controller, user controller, visitor controller, etc.) to decrease the probability of breaking authorization for the app.

**Comment by jakub-zawislak** [comment]
I don't want to stick to single JS select library.

I wonder if there is a need for creating such controller automatically. Code of controllers will depend on chosen JS library and source of data. 

BTW. I don't see that Choices library supports ajax search, it can only load data via ajax on init.

This is my idea:

1. Create an option that will disable [initial select validation](https://github.com/jakub-zawislak/formex/blob/master/lib/formex/builder.ex#L122)
    ```elixir
    |> add(:client_id, :select, choices_validation: false)
   ```
2. Use it by adding options related to chosen JS library. Example usage with [Ajax-Bootstrap-Select](https://github.com/truckingsim/Ajax-Bootstrap-Select):
    ```elixir
    |> add(:client_id, :select, choices_validation: false,
      phoenix_opts: [
        data: [
          live_search: true,
          abs_ajax_url: "YOUR URL",
        ]
      ]
    )
    ```

It will cannot be used with a SelectAssoc module. All that this module does is loading choices from a database. On the other hand, the SelectAssoc could be used in an automatically created controller.

**Comment by jakub-zawislak** [comment]
See https://hexdocs.pm/formex/guides.html#using-a-select-picker-plugin-with-ajax-search

**Comment by jakub-zawislak** [comment]
I have added a function that you can use in controller
https://hexdocs.pm/formex_ecto/Formex.Ecto.CustomField.SelectAssoc.html#search/3
It searches choices using already provided data in your Type, but you still need to write some code to get it work with your select picker library.
